/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yellowcab;

import java.awt.BorderLayout;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Isrg
 */

public class main extends javax.swing.JFrame {
    

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_rider_type = new javax.swing.ButtonGroup();
        bg_cab_type = new javax.swing.ButtonGroup();
        bg_mop = new javax.swing.ButtonGroup();
        bg_gender = new javax.swing.ButtonGroup();
        new_rider_type = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        home = new javax.swing.JTabbedPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tf_n_name = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_n_mobile = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cb_n_persons = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        tf_n_email = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        rb_n_female = new javax.swing.JRadioButton();
        rb_n_male = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        rb_n_yc = new javax.swing.JRadioButton();
        rb_n_suv = new javax.swing.JRadioButton();
        rb_n_royal = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        tf_n_p_point = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tf_n_d_point = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tf_n_p_time = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tf_n_p_date = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        rb_n_rider_female = new javax.swing.JRadioButton();
        rb_n_rider_male = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        rb_n_pm_dc = new javax.swing.JRadioButton();
        rb_n_pm_cc = new javax.swing.JRadioButton();
        rb_n_pm_cash = new javax.swing.JRadioButton();
        book_now = new javax.swing.JButton();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        tf_m_mobileid = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        tf_m_name = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tf_m_mobile = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        cb_m_persons = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        tf_m_email = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        rb_m_female = new javax.swing.JRadioButton();
        tf_m_male = new javax.swing.JRadioButton();
        tf_hbok = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        rb_m_yc = new javax.swing.JRadioButton();
        rb_m_suv = new javax.swing.JRadioButton();
        rb_m_royal = new javax.swing.JRadioButton();
        jLabel27 = new javax.swing.JLabel();
        tf_m_p_point = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        tf_m_d_point = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        tf_m_p_time = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        tf_m_p_date = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        rb_m_rider_female = new javax.swing.JRadioButton();
        rb_m_rider_male = new javax.swing.JRadioButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        rb_m_pm_dc = new javax.swing.JRadioButton();
        rb_m_pm_cc = new javax.swing.JRadioButton();
        rb_m_pm_cash = new javax.swing.JRadioButton();
        bt_modify = new javax.swing.JButton();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        report = new javax.swing.JTable();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        tf_c_mobileid = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        tf_c_name = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        tf_c_mobile = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        rb_c_persons = new javax.swing.JComboBox();
        jLabel37 = new javax.swing.JLabel();
        tf_c_email = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        tf_c_hbok = new javax.swing.JTextField();
        bt_cancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yellowcab/yellowcab.png"))); // NOI18N

        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yellowcab/animated_cab.gif"))); // NOI18N
        jLabel4.setAlignmentY(0.0F);

        jLabel5.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel5.setText("Welcome to");

        jLabel6.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("Yellow");

        jLabel7.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel7.setText("Cab");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(133, 133, 133))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(154, 154, 154)
                    .addComponent(jLabel5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel6)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel7)
                    .addContainerGap(394, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7))
                    .addContainerGap(467, Short.MAX_VALUE)))
        );

        home.addTab("Home", jLayeredPane1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel8.setText("Customer Name:");

        jLabel9.setText("Mobile:");

        jLabel10.setText("Number of Persons:");

        cb_n_persons.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));

        jLabel11.setText("Email:");

        jLabel12.setText("Gender:");

        bg_gender.add(rb_n_female);
        rb_n_female.setText("Female");

        bg_gender.add(rb_n_male);
        rb_n_male.setText("Male");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_n_name)
                            .addComponent(cb_n_persons, 0, 243, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_n_mobile))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_n_email))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rb_n_female)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_n_male)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_n_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(tf_n_mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(cb_n_persons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(tf_n_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rb_n_female)
                        .addComponent(rb_n_male))))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Booking Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel13.setText("Type of Cab:");

        bg_cab_type.add(rb_n_yc);
        rb_n_yc.setText("Yellow Cab");

        bg_cab_type.add(rb_n_suv);
        rb_n_suv.setText("Yellow SUV");

        bg_cab_type.add(rb_n_royal);
        rb_n_royal.setText("Royal Yellow ");

        jLabel14.setText("Pick-up Point:");

        tf_n_p_point.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_n_p_pointActionPerformed(evt);
            }
        });

        jLabel15.setText("Drop-point:");

        jLabel16.setText("Pick-up Time:");

        jLabel17.setText("Pick-up Date:");

        jLabel18.setText("Rider Type:");

        bg_rider_type.add(rb_n_rider_female);
        rb_n_rider_female.setText("Female");

        bg_rider_type.add(rb_n_rider_male);
        rb_n_rider_male.setText("Male");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb_n_yc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_n_suv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb_n_royal))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tf_n_p_point)
                    .addComponent(tf_n_p_time, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_n_d_point, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                    .addComponent(tf_n_p_date))
                .addGap(36, 36, 36))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(rb_n_rider_female)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb_n_rider_male))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(rb_n_yc)
                    .addComponent(rb_n_suv)
                    .addComponent(rb_n_royal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_n_p_point, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(tf_n_d_point, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_n_p_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)
                        .addComponent(tf_n_p_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(rb_n_rider_female)
                    .addComponent(rb_n_rider_male))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Payment Details:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel19.setText("Payment Mode:");

        bg_mop.add(rb_n_pm_dc);
        rb_n_pm_dc.setText("Debit Card");

        bg_mop.add(rb_n_pm_cc);
        rb_n_pm_cc.setText("Credit Card");

        bg_mop.add(rb_n_pm_cash);
        rb_n_pm_cash.setText("Cash");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_n_pm_dc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_n_pm_cc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_n_pm_cash)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(rb_n_pm_dc)
                    .addComponent(rb_n_pm_cc)
                    .addComponent(rb_n_pm_cash))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        book_now.setText("Book Now");
        book_now.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_nowActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(book_now, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(book_now)
                        .addGap(0, 680, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 803, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(book_now)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        home.addTab("New Booking", jLayeredPane2);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Booking", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel20.setText("Mobile or Booking ID:");

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_m_mobileid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tf_m_mobileid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel21.setText("Customer Name:");

        jLabel22.setText("Mobile:");

        jLabel23.setText("Number of Persons:");

        cb_m_persons.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));

        jLabel24.setText("Email:");

        jLabel25.setText("Gender:");

        bg_gender.add(rb_m_female);
        rb_m_female.setText("Female");
        rb_m_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_m_femaleActionPerformed(evt);
            }
        });

        bg_gender.add(tf_m_male);
        tf_m_male.setText("Male");

        tf_hbok.setEditable(false);

        jLabel38.setText("BID:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel21)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_m_name)
                            .addComponent(cb_m_persons, 0, 243, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_m_mobile))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel38))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(tf_hbok)
                                        .addContainerGap())
                                    .addComponent(tf_m_email)))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(rb_m_female)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_m_male)
                        .addGap(0, 530, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tf_m_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(tf_m_mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(cb_m_persons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(tf_m_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rb_m_female)
                        .addComponent(tf_m_male))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_hbok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel38))))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Booking Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel26.setText("Type of Cab:");

        bg_cab_type.add(rb_m_yc);
        rb_m_yc.setText("Yellow Cab");

        bg_cab_type.add(rb_m_suv);
        rb_m_suv.setText("Yellow SUV");
        rb_m_suv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_m_suvActionPerformed(evt);
            }
        });

        bg_cab_type.add(rb_m_royal);
        rb_m_royal.setText("Royal Yellow ");

        jLabel27.setText("Pick-up Point:");

        tf_m_p_point.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_m_p_pointActionPerformed(evt);
            }
        });

        jLabel28.setText("Drop-point:");

        jLabel29.setText("Pick-up Time:");

        jLabel30.setText("Pick-up Date:");

        jLabel31.setText("Rider Type:");

        new_rider_type.add(rb_m_rider_female);
        rb_m_rider_female.setText("Female");

        new_rider_type.add(rb_m_rider_male);
        rb_m_rider_male.setText("Male");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_m_yc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_m_suv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_m_royal))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tf_m_p_point)
                            .addComponent(tf_m_p_time, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addGap(1, 1, 1)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tf_m_p_date, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                            .addComponent(tf_m_d_point)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(18, 18, 18)
                        .addComponent(rb_m_rider_female)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_m_rider_male)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(rb_m_yc)
                    .addComponent(rb_m_suv)
                    .addComponent(rb_m_royal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(tf_m_p_point, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(tf_m_d_point, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_m_p_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel30)
                        .addComponent(tf_m_p_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(rb_m_rider_female)
                    .addComponent(rb_m_rider_male))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Payment Details:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel36.setText("Payment Mode:");

        bg_mop.add(rb_m_pm_dc);
        rb_m_pm_dc.setText("Debit Card");

        bg_mop.add(rb_m_pm_cc);
        rb_m_pm_cc.setText("Credit Card");

        bg_mop.add(rb_m_pm_cash);
        rb_m_pm_cash.setText("Cash");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_m_pm_dc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_m_pm_cc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_m_pm_cash)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(rb_m_pm_dc)
                    .addComponent(rb_m_pm_cc)
                    .addComponent(rb_m_pm_cash))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bt_modify.setText("Modify");
        bt_modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_modifyActionPerformed(evt);
            }
        });

        jLayeredPane3.setLayer(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jPanel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jPanel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jPanel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(bt_modify, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 803, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bt_modify)))
                .addContainerGap())
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_modify)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        home.addTab("Modify Booking", jLayeredPane3);

        report.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.No", "Book ID", "Name", "Mobile", "Persons", "Email", "Gender", "Cab Type", "P Point", "D Point", "P Time", "P Date", "Rider Type", "MOP"
            }
        ));
        jScrollPane1.setViewportView(report);
        if (report.getColumnModel().getColumnCount() > 0) {
            report.getColumnModel().getColumn(5).setResizable(false);
        }

        jLayeredPane4.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                .addContainerGap())
        );

        home.addTab("Booking Report", jLayeredPane4);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Booking", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel32.setText("Mobile or Booking ID:");

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_c_mobileid, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(tf_c_mobileid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel33.setText("Customer Name:");

        jLabel34.setText("Mobile:");

        jLabel35.setText("Number of Persons:");

        rb_c_persons.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));

        jLabel37.setText("Email:");

        jLabel39.setText("Book ID:");

        tf_c_hbok.setEditable(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(jLabel33)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_c_name)
                    .addComponent(rb_c_persons, 0, 243, Short.MAX_VALUE)
                    .addComponent(tf_c_hbok))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_c_mobile, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_c_email))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(tf_c_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(tf_c_mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel35)
                        .addComponent(rb_c_persons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel37)
                        .addComponent(tf_c_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39)
                    .addComponent(tf_c_hbok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        bt_cancel.setText("Cancel  Booking");
        bt_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelActionPerformed(evt);
            }
        });

        jLayeredPane5.setLayer(jPanel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(jPanel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(bt_cancel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane5Layout = new javax.swing.GroupLayout(jLayeredPane5);
        jLayeredPane5.setLayout(jLayeredPane5Layout);
        jLayeredPane5Layout.setHorizontalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jLayeredPane5Layout.createSequentialGroup()
                        .addComponent(bt_cancel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jLayeredPane5Layout.setVerticalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_cancel)
                .addContainerGap(286, Short.MAX_VALUE))
        );

        home.addTab("Cancel Booking", jLayeredPane5);

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel2.setText("Contact 24x7 ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("1800-1100-MEGHA");

        jMenu1.setText("File");

        jMenuItem2.setText("Logout");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(home))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(31, 31, 31)))
                .addGap(6, 6, 6)
                .addComponent(home))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
int return_code=JOptionPane.showConfirmDialog(this,"Are you sure you want to Logout?");
if(return_code==0){
        System.exit(0);
}

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
int return_code=JOptionPane.showConfirmDialog(this,"Are you sure you want to Exit?");
if(return_code==0){
        System.exit(0);
}
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
int tabno=home.getSelectedIndex();
DefaultTableModel model=(DefaultTableModel) report.getModel();
model.setRowCount(0);

int index_id=1;

if(tabno==3)
{
    JOptionPane.showMessageDialog(this, "Please wait loading...");
    
     
    
    this.setTitle("Booking Report");
  try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/yello_cab","root","bmvb");
            Statement stmt=null;
            stmt=con.createStatement();
            ResultSet rs=null;
            String q2="Select * from yc_table order by book_id desc;";
            rs=stmt.executeQuery(q2);
            while(rs.next()) {
model.addRow(new Object[]{index_id,rs.getString("book_id"),rs.getString("cu_name"),rs.getString("mobile"),rs.getString("no_persons"), rs.getString("email"), rs.getString("gender"), rs.getString("cab_type"), rs.getString("p_point"), rs.getString("d_point"), rs.getString("p_time"), rs.getString("p_date"), rs.getString("rider_type"), rs.getString("payment_mode")});            
            index_id++;
            } 
            stmt.close();
   
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
   
}
    }//GEN-LAST:event_homeMouseClicked

    private void tf_m_p_pointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_m_p_pointActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_m_p_pointActionPerformed

    private void rb_m_suvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_m_suvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_m_suvActionPerformed

    private void rb_m_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_m_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_m_femaleActionPerformed

    private void book_nowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_nowActionPerformed
        String custname=tf_n_name.getText();
        String mobile=tf_n_mobile.getText();
        String noperson=(String) cb_n_persons.getSelectedItem();
        String email=tf_n_email.getText();
        String gender=null;
        String cab_type=null;
        String is_valid="true";
        //gender
        if(rb_n_female.isSelected())
        gender="Female";
        else
        if(rb_n_male.isSelected())
        gender="Male";
        //type of cab
        if(rb_n_yc.isSelected())
        cab_type="yc";
        else
        if(rb_n_suv.isSelected())
        cab_type="suv";
        else
        cab_type="royal";
        String pickuppoint=tf_n_p_point.getText();
        String droppoint=tf_n_d_point.getText();
        String time=tf_n_p_time.getText();
        String pickupdate=tf_n_p_date.getText();
        //Rider
        String rider=null;
        if(rb_n_rider_male.isSelected())
        rider="male";
        else
        if(rb_n_rider_female.isSelected())
        rider="female";
        //payment
        String mop=null;

        if(rb_n_pm_dc.isSelected())
        mop="dc";
        else
        if(rb_n_pm_cc.isSelected())
        mop="cc";
        else
        gender="cash";

        //validation
        if(custname.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the Name ");
            is_valid="false";
        }
        else
        if(mobile.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the mobile number ");
            is_valid="false";
        } else
        if(noperson.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select the number of person ");
            is_valid="false";
        }
        else
        if(email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the email ");
            is_valid="false";
        }
        else if(gender==null) {
            JOptionPane.showMessageDialog(this, "Please select gender type ");
            is_valid="false";
        } else if(cab_type.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select the type cab ");
            is_valid="false";
        }
        else if(pickuppoint.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the pick up address ");
            is_valid="false";
        }
        else if(droppoint.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the drop point ");
            is_valid="false";
        }
        else if(time.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the time ");
            is_valid="false";
        }
        else
        if(pickupdate.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the pick-up Date ");
            is_valid="false";
        }
        else
        if(rider==null) {
            JOptionPane.showMessageDialog(this, "Please select the rider type ");
            is_valid="false";
        }
        else
        if(mop==null) {
            JOptionPane.showMessageDialog(this, "Please select the payment type ");
            is_valid="false";
        }

        if(is_valid.equals("true"))
        {

            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/yello_cab","root","bmvb");
                Statement stmt=null;
                stmt=con.createStatement();
                String query="INSERT INTO yc_table(cu_name, mobile, no_persons, email, gender, cab_type, p_point, d_point, p_time, p_date, rider_type, payment_mode) VALUES ('"+custname+"', '"+mobile+"',"+noperson+",'"+email+"','"+gender+"','"+cab_type+"','"+pickuppoint+"','"+droppoint+"','"+time+"','"+pickupdate+"','"+rider+"','"+mop+"');";
                int qexecute=stmt.executeUpdate(query);

                JOptionPane.showMessageDialog(this, "Thank you!\nYour booking has been successfully made");
                book_now.setEnabled(false);
            } catch (Exception e) {

                JOptionPane.showMessageDialog(this, e.getMessage());
            }

        }
    }//GEN-LAST:event_book_nowActionPerformed

    private void tf_n_p_pointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_n_p_pointActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_n_p_pointActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
if(tf_m_mobileid.getText().isEmpty())   {
    JOptionPane.showMessageDialog(this, " Please enter Mobile no. or booking id ");
} else {
    
    
     try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/yello_cab","root","bmvb");
            Statement stmt=null;
            stmt=con.createStatement();
            ResultSet rs=null;
            String q2="Select * from yc_table where mobile='"+tf_m_mobileid.getText()+"' OR book_id='"+tf_m_mobileid.getText()+"' limit 1;";
            rs=stmt.executeQuery(q2);
            if(rs.next()) {
                bt_modify.setEnabled(true);
                tf_m_name.setText(rs.getString("cu_name"));
                tf_m_mobile.setText(rs.getString("mobile"));
                tf_m_email.setText(rs.getString("email"));
                tf_m_p_point.setText(rs.getString("p_point"));
                tf_m_d_point.setText(rs.getString("d_point"));
                tf_m_p_time.setText(rs.getString("p_time"));
                tf_m_p_date.setText(rs.getString("p_date"));
                //gender
                if(rs.getString("gender").equals("Male"))
                  {
                      tf_m_male.setSelected(true);
                  } else {
                      rb_m_female.setSelected(true);
                  }
                
                //cab type
                  if(rs.getString("cab_type").equals("yc"))
                  {
                      rb_m_yc.setSelected(true);
                  } else
                  if (rs.getString("cab_type").equals("suv")){
                      rb_m_suv.setSelected(true);
                  } else
                  if (rs.getString("cab_type").equals("royal")){
                      rb_m_royal.setSelected(true);
                  }
                  
                  // rider type
                  System.out.print(rs.getString("rider_type"));
                  if (rs.getString("rider_type").equals("male")){
                      rb_m_rider_male.setSelected(true);
                  } else
                 {
                      rb_m_rider_female.setSelected(true);
                  }
                  // mode of payment
                               
                  if (rs.getString("payment_mode").equals("dc")){
                      rb_m_pm_dc.setSelected(true);
                  } else
                  if (rs.getString("payment_mode").equals("cc")){
                      rb_m_pm_cc.setSelected(true);
                  } else
                  if (rs.getString("payment_mode").equals("cash")){
                      rb_m_pm_cash.setSelected(true);
                  }                  
                 tf_hbok.setText(rs.getString("book_id"));
                  
            } else {
                JOptionPane.showMessageDialog(null, "Sorry!\nWe haven't found any records.");
                bt_modify.setEnabled(false);
                       }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            bt_modify.setEnabled(false);


        }
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bt_modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modifyActionPerformed
        String custname=tf_m_name.getText();
        String mobile=tf_m_mobile.getText();
        String noperson=(String) cb_m_persons.getSelectedItem();
        String email=tf_m_email.getText();
        String hbok=tf_hbok.getText();
        String gender=null;
        String cab_type=null;
        String is_valid="true";
        //gender
        if(rb_m_female.isSelected())
        gender="Female";
        else
        if(tf_m_male.isSelected())
        gender="Male";
        //type of cab
        if(rb_m_yc.isSelected())
        cab_type="yc";
        else
        if(rb_m_suv.isSelected())
        cab_type="suv";
        else
        cab_type="royal";
        String pickuppoint=tf_m_p_point.getText();
        String droppoint=tf_m_d_point.getText();
        String time=tf_m_p_time.getText();
        String pickupdate=tf_m_p_date.getText();
        //Rider
        String rider=null;
        if(rb_m_rider_male.isSelected())
        rider="male";
        else
        if(rb_m_rider_female.isSelected())
        rider="female";
        //payment
        String mop=null;

        if(rb_m_pm_dc.isSelected())
        mop="dc";
        else
        if(rb_m_pm_cc.isSelected())
        mop="cc";
        else
        gender="cash";

        //validation
        if(custname.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the Name ");
            is_valid="false";
        }
        else
        if(mobile.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the mobile number ");
            is_valid="false";
        } else
        if(noperson.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select the number of person ");
            is_valid="false";
        }
        else
        if(email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the email ");
            is_valid="false";
        }
        else if(gender==null) {
            JOptionPane.showMessageDialog(this, "Please select gender type ");
            is_valid="false";
        } else if(cab_type.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select the type cab ");
            is_valid="false";
        }
        else if(pickuppoint.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the pick up address ");
            is_valid="false";
        }
        else if(droppoint.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the drop point ");
            is_valid="false";
        }
        else if(time.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the time ");
            is_valid="false";
        }
        else
        if(pickupdate.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the pick-up Date ");
            is_valid="false";
        }
        else
        if(rider==null) {
            JOptionPane.showMessageDialog(this, "Please select the rider type ");
            is_valid="false";
        }
        else
        if(mop==null) {
            JOptionPane.showMessageDialog(this, "Please select the payment type ");
            is_valid="false";
        }

        if(is_valid.equals("true"))
        {

            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/yello_cab","root","bmvb");
                Statement stmt=null;
                stmt=con.createStatement();
                String query="update yc_table set cu_name='"+custname+"', mobile='"+mobile+"', no_persons="+noperson+", email='"+email+"', gender='"+gender+"', cab_type='"+cab_type+"', p_point='"+pickuppoint+"', d_point='"+droppoint+"', p_time='"+time+"', p_date='"+pickupdate+"', rider_type='"+rider+"', payment_mode='"+mop+"' where book_id="+hbok+";";
                int qexecute=stmt.executeUpdate(query);
                JOptionPane.showMessageDialog(this, "Thank you!\nYour booking has been successfully modified");
                bt_modify.setEnabled(false);
            } catch (Exception e) {

                JOptionPane.showMessageDialog(this, e.getMessage());
            }

        }
    }//GEN-LAST:event_bt_modifyActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
if(tf_c_mobileid.getText().isEmpty())   {
    JOptionPane.showMessageDialog(this, " Please enter Mobile no. or booking id ");
} else {
    
    
     try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/yello_cab","root","bmvb");
            Statement stmt=null;
            stmt=con.createStatement();
            ResultSet rs=null;
            String q2="Select * from yc_table where mobile='"+tf_c_mobileid.getText()+"' OR book_id='"+tf_c_mobileid.getText()+"' limit 1;";
            rs=stmt.executeQuery(q2);
            if(rs.next()) {
                bt_cancel.setEnabled(true);
                tf_c_name.setText(rs.getString("cu_name"));
                tf_c_mobile.setText(rs.getString("mobile"));
                tf_c_email.setText(rs.getString("email"));
                rb_c_persons.setSelectedIndex(Integer.parseInt(rs.getString("no_persons")));
                 tf_c_hbok.setText(rs.getString("book_id"));
                  
            } else {
                JOptionPane.showMessageDialog(null, "Sorry!\nWe haven't found any records.");
                bt_modify.setEnabled(false);
                       }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            bt_modify.setEnabled(false);


        }
}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void bt_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelActionPerformed
int hbok=Integer.parseInt(tf_c_hbok.getText());
        try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/yello_cab","root","bmvb");
                Statement stmt=null;
                stmt=con.createStatement();
                String query="delete from yc_table where book_id="+hbok+";";
                int qexecute=stmt.executeUpdate(query);
                JOptionPane.showMessageDialog(this, "Thank you!\nYour booking has been successfully canceled");
                bt_cancel.setEnabled(false);
            } catch (Exception e) {

                JOptionPane.showMessageDialog(this, e.getMessage());
            }
    }//GEN-LAST:event_bt_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_cab_type;
    private javax.swing.ButtonGroup bg_gender;
    private javax.swing.ButtonGroup bg_mop;
    private javax.swing.ButtonGroup bg_rider_type;
    private javax.swing.JButton book_now;
    private javax.swing.JButton bt_cancel;
    private javax.swing.JButton bt_modify;
    private javax.swing.JComboBox cb_m_persons;
    private javax.swing.JComboBox cb_n_persons;
    private javax.swing.JTabbedPane home;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup new_rider_type;
    private javax.swing.JComboBox rb_c_persons;
    private javax.swing.JRadioButton rb_m_female;
    private javax.swing.JRadioButton rb_m_pm_cash;
    private javax.swing.JRadioButton rb_m_pm_cc;
    private javax.swing.JRadioButton rb_m_pm_dc;
    private javax.swing.JRadioButton rb_m_rider_female;
    private javax.swing.JRadioButton rb_m_rider_male;
    private javax.swing.JRadioButton rb_m_royal;
    private javax.swing.JRadioButton rb_m_suv;
    private javax.swing.JRadioButton rb_m_yc;
    private javax.swing.JRadioButton rb_n_female;
    private javax.swing.JRadioButton rb_n_male;
    private javax.swing.JRadioButton rb_n_pm_cash;
    private javax.swing.JRadioButton rb_n_pm_cc;
    private javax.swing.JRadioButton rb_n_pm_dc;
    private javax.swing.JRadioButton rb_n_rider_female;
    private javax.swing.JRadioButton rb_n_rider_male;
    private javax.swing.JRadioButton rb_n_royal;
    private javax.swing.JRadioButton rb_n_suv;
    private javax.swing.JRadioButton rb_n_yc;
    private javax.swing.JTable report;
    private javax.swing.JTextField tf_c_email;
    private javax.swing.JTextField tf_c_hbok;
    private javax.swing.JTextField tf_c_mobile;
    private javax.swing.JTextField tf_c_mobileid;
    private javax.swing.JTextField tf_c_name;
    private javax.swing.JTextField tf_hbok;
    private javax.swing.JTextField tf_m_d_point;
    private javax.swing.JTextField tf_m_email;
    private javax.swing.JRadioButton tf_m_male;
    private javax.swing.JTextField tf_m_mobile;
    private javax.swing.JTextField tf_m_mobileid;
    private javax.swing.JTextField tf_m_name;
    private javax.swing.JTextField tf_m_p_date;
    private javax.swing.JTextField tf_m_p_point;
    private javax.swing.JTextField tf_m_p_time;
    private javax.swing.JTextField tf_n_d_point;
    private javax.swing.JTextField tf_n_email;
    private javax.swing.JTextField tf_n_mobile;
    private javax.swing.JTextField tf_n_name;
    private javax.swing.JTextField tf_n_p_date;
    private javax.swing.JTextField tf_n_p_point;
    private javax.swing.JTextField tf_n_p_time;
    // End of variables declaration//GEN-END:variables
}
